name = "LinearAlgebraForCAP"
uuid = "3dc4824f-14ac-4ab7-8a60-75dbcd4a9d60"
authors = ["Kamal Saleh <kamal.saleh@web.de>"]
version = "0.1.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
MatricesForHomalg = "29b9b1b6-efa6-450e-8188-a5a2c25df071"
CAP = "d64df2ee-d2bb-46f4-8cbc-f03bb858f8cb"
MonoidalCategories = "bfd98c86-782f-4b94-909f-74167f1eb613"

[compat]
julia = "1.9"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
